"""add return_date for round trips

Revision ID: 727e639f13e1
Revises: c7f3c19d7a4e
Create Date: 2026-08-13 11:33:30.737954
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '727e639f13e1'
down_revision: str | None = 'c7f3c19d7a4e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###
