"""initial schema

Revision ID: c7f3c19d7a4e
Revises: 
Create Date: 2026-08-12 09:13:09.279730
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c7f3c19d7a4e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disclaimer_acknowledgements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_token', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('search_id', sa.String(length=32), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disclaimer_acknowledgements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disclaimer_acknowledgements_client_token'), ['client_token'], unique=False)

    op.create_table('offer_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('origin', sa.String(length=4), nullable=False),
    sa.Column('destination', sa.String(length=4), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('cabin', sa.String(length=24), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('offer_count', sa.Integer(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'origin', 'destination', 'departure_date', 'cabin', 'adults', name='uq_offer_cache_key')
    )
    with op.batch_alter_table('offer_cache', schema=None) as batch_op:
        batch_op.create_index('ix_offer_cache_fetched', ['fetched_at'], unique=False)

    op.create_table('price_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=4), nullable=False),
    sa.Column('destination', sa.String(length=4), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('offer_count', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_observations', schema=None) as batch_op:
        batch_op.create_index('ix_price_obs_market', ['origin', 'destination', 'departure_date', 'observed_at'], unique=False)

    op.create_table('route_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_iata', sa.String(length=4), nullable=False),
    sa.Column('onward_iata', sa.String(length=4), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('times_probed', sa.Integer(), nullable=False),
    sa.Column('times_anomalous', sa.Integer(), nullable=False),
    sa.Column('times_empty', sa.Integer(), nullable=False),
    sa.Column('best_savings', sa.Float(), nullable=True),
    sa.Column('last_probed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hub_iata', 'onward_iata', name='uq_route_candidate_edge')
    )
    with op.batch_alter_table('route_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_route_candidate_hub_score', ['hub_iata', 'score'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_candidates_hub_iata'), ['hub_iata'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_candidates_onward_iata'), ['onward_iata'], unique=False)

    op.create_table('search_queries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=4), nullable=False),
    sa.Column('destination', sa.String(length=4), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('cabin', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('baseline_price', sa.Float(), nullable=True),
    sa.Column('best_hidden_price', sa.Float(), nullable=True),
    sa.Column('best_savings', sa.Float(), nullable=True),
    sa.Column('candidates_planned', sa.Integer(), nullable=False),
    sa.Column('candidates_probed', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.create_index('ix_search_query_route', ['origin', 'destination', 'departure_date'], unique=False)

    op.create_table('hidden_city_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=4), nullable=False),
    sa.Column('deplane_iata', sa.String(length=4), nullable=False),
    sa.Column('ticketed_iata', sa.String(length=4), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('baseline_price', sa.Float(), nullable=False),
    sa.Column('savings', sa.Float(), nullable=False),
    sa.Column('savings_percent', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('carrier', sa.String(length=8), nullable=False),
    sa.Column('deplane_segment_index', sa.Integer(), nullable=False),
    sa.Column('segments_before_target', sa.Integer(), nullable=False),
    sa.Column('layover_minutes_at_target', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('risk_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('itinerary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['search_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hidden_city_findings', schema=None) as batch_op:
        batch_op.create_index('ix_finding_route', ['origin', 'deplane_iata', 'departure_date'], unique=False)
        batch_op.create_index('ix_finding_savings', ['savings'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hidden_city_findings', schema=None) as batch_op:
        batch_op.drop_index('ix_finding_savings')
        batch_op.drop_index('ix_finding_route')

    op.drop_table('hidden_city_findings')
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.drop_index('ix_search_query_route')

    op.drop_table('search_queries')
    with op.batch_alter_table('route_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_candidates_onward_iata'))
        batch_op.drop_index(batch_op.f('ix_route_candidates_hub_iata'))
        batch_op.drop_index('ix_route_candidate_hub_score')

    op.drop_table('route_candidates')
    with op.batch_alter_table('price_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_price_obs_market')

    op.drop_table('price_observations')
    with op.batch_alter_table('offer_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_offer_cache_fetched')

    op.drop_table('offer_cache')
    with op.batch_alter_table('disclaimer_acknowledgements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disclaimer_acknowledgements_client_token'))

    op.drop_table('disclaimer_acknowledgements')
    # ### end Alembic commands ###
